
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Set the Username Environment Variable
    env:
      LT_USERNAME: "taufiq.maredia786"
    command: echo export $LT_USERNAME

  - name: Set the Access Key Environment Variable
    env:
      LT_ACCESS_KEY: "tS0UIcAHxNNsAcA4qjmIaaEgCoJVnnxFfb5VmIlB980N9hUJaT"
    command: echo export $LT_ACCESS_KEY  
  
  - init: mvn install -Dsuite=parallel.xml # runs during prebuild
    command: echo 'Please check your test on https://automation.lambdatest.com/'


vscode:
  extensions:
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - redhat.java
